def divided_by(a,b):
    return a/b

try:
    print(divided_by(50,0))
except Exception as e:
    print('Error is:', e);